Repository HDFGroup/vol-rest, pull requests merged in 2023-11, with the labels that each got.

#49 Support H5Dset_extent
  src/rest_vol.c
  src/rest_vol.h
  src/rest_vol_attr.c
  src/rest_vol_dataset.c
  src/rest_vol_datatype.c
  src/rest_vol_file.c
  src/rest_vol_group.c
Labels: enhancement

#74 Implement H5Fget_obj_count without global info
  src/rest_vol_file.c
Labels: enhancement

#81 Set connection info even with non-default FAPL
  src/rest_vol.c
  src/rest_vol_file.c
Labels: bug

#98 Fix bad URL when linking VOL multiple times
  src/rest_vol.c
Labels: bug, testing

#99 Fix segfault on H5Dset_extent
  src/rest_vol_dataset.c
Labels: bug, testing

#97 Remove H5Fget_obj_count from unused API test
  test/test_rest_vol.c
Labels: bug, testing

#100 Fix segfault on VOL termination
  src/rest_vol.c
Labels: bug, testing

#101 Remove HSDS caching in CI
  .github/workflows/main.yml
Labels: enhancement, testing

#72 Implement type conversion for simple numeric types
  src/rest_vol.c
  src/rest_vol.h
  src/rest_vol_dataset.c
  src/rest_vol_datatype.c
  src/rest_vol_datatype.h
Labels: enhancement

#94 Fix H5Ovisit on files/groups, dangling links in link tests
  src/rest_vol_object.c
  test/test_rest_vol.c
Labels: bug

#95 Implement H5Arename/H5Arename_by_name by copy
  src/rest_vol_attr.c
  test/test_rest_vol.c
Labels: enhancement, testing

#104 Remove FetchContent builds from CI
  .github/workflows/main.yml
Labels: testing
